name: CI

on:
  schedule:
    - cron:  '05 16 * * *'
  workflow_dispatch:
      inputs:
        deployDocs:
          description: 'Deploy API Documentation'
          required: true
          default: 'True'
          type: choice
          options:
          - 'True'
          - 'False'

jobs:
   check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
    - uses: actions/checkout@v2
    - id: should_run
      continue-on-error: true
      name: check latest commit is less than a day
      if: ${{ github.event_name == 'schedule' }}
      run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"
   log-the-inputs:
     needs: check_date
     if: ${{ (github.event_name == 'workflow_dispatch' && inputs.deployDocs == 'True' ) || (github.event_name == 'schedule' && needs.check_date.outputs.should_run != 'false') }}
     runs-on: ubuntu-latest
     steps:
       - run: |
           echo "Log level: ${{ inputs.deployDocs }}"
