# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
      inputs:
        deployDocs:
          description: 'Deploy API Documentation'
          required: true
          default: 'True'
          type: choice
          options:
          - 'True'
          - 'False'

jobs:
  log-the-inputs:
    if: ${{ inputs.deployDocs == 'True' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: ${{ inputs.deployDocs }}"
